# .github/workflows/tests.yml
name: Run tests
on:
  push:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-16.04, ubuntu-18.04, ubuntu-20.04,
          macos-10.15, windows-2019
        ]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-20.04
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install
      run: pip install .
    - name: Run tests
      run: pytest
